name: xsighub_mobile
description: App móvil que se conecta al sistema Hub y registra las firmas de los usuarios.
publish_to: "none"
version: 0.2.1-beta

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  mask_text_input_formatter: ^2.4.0
  qr_code_scanner: ^1.0.1
  syncfusion_flutter_signaturepad: ^21.2.3
  flutter_colorpicker: ^1.0.3
  flutter_markdown: ^0.6.14
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.1
  collection: ^1.17.0
  socket_io_client: ^2.0.2
  flutter_easyloading: ^3.0.5
  markdown: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/1.5x/logo.png
    - assets/images/2.0x/logo.png
    - assets/images/3.0x/logo.png
    - assets/images/4.0x/logo.png
