name: Build APKs

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Build APKs
        run: flutter build apk --split-per-abi

      - name: Upload APKs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          asset_name: |
            xsighub-armeabi-v7a-release-${{ github.ref }}
            xsighub-arm64-v8a-release-${{ github.ref }}
            xsighub-x86_64-release-${{ github.ref }}
          asset_content_type: application/vnd.android.package-archive
